# Generated by Django 3.2.3 on 2021-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Food', 'Food'), ('Cloths', 'Cloths'), ('CD/DVD', 'CD/DVD'), ('Books', 'Books'), ('Imported', 'Imported'), ('Pants', 'Pants')], max_length=10)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
