# Generated by Django 3.2.3 on 2021-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
