# Generated by Django 3.2.3 on 2021-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210702_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
