# Generated by Django 3.2.3 on 2021-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210702_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
