# Generated by Django 3.2.3 on 2021-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210702_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='category',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Food', 'Food'), ('Cloths', 'Cloths'), ('CD/DVD', 'CD/DVD'), ('Books', 'Books'), ('Imported', 'Imported')], max_length=10),
        ),
    ]
